# fly.toml app configuration file generated for obesity-risk-api
app = "obesity-risk-api"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.backend"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[mounts]
  source = "obesity_models"
  destination = "/app/models"

[[services.ports]]
  port = 80
  handlers = ["http"]

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[[services.http_checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http" 