# fly.toml app configuration file for obesity-risk-api
app = "obesity-risk-api"
primary_region = "ord"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[env]
  PORT = "8000"
  PYTHONPATH = "."
  PYTHONUNBUFFERED = "1"
  DEBUG = "true"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[mounts]
  source = "obesity_models"
  destination = "/app/models"

[[services.ports]]
  port = 80
  handlers = ["http"]

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[[services.http_checks]]
  interval = "15s"
  timeout = "10s"
  grace_period = "30s"
  method = "get"
  path = "/"
  protocol = "http"
  restart_limit = 3 