services:
  - type: web
    name: obesity-risk-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p models logs data/train
    startCommand: python -m uvicorn test_api_render:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - render-requirements.txt
        - start.sh
        - render.yaml 