services:
  - type: web
    name: obesity-risk-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r render-requirements.txt
      mkdir -p models logs data/train
    startCommand: bash ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: 10000
    healthCheckPath: /health
    buildFilter:
      paths:
        - src/**
        - render-requirements.txt
        - start.sh
        - render.yaml 